name = "ada_spark_workflow"
description = "A demo of best practices for open-source Ada/SPARK development"
version = "0.1.0-dev"

authors = ["The Alire Team"]
maintainers = ["fabien.chouteau@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]
tags = ["demo", "example", "spark", "coverage", "tests"]
website = "alire.ada.dev"
licenses = "MIT"

[[depends-on]]
resources = "~0.1.0"
gnatprove = "^12.1.1"

[[pins]]
resources = { url='https://github.com/alire-project/resources' }
